# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A KNN function using Rcpp
#' @description A KNN(K-Nearest Neighbor) classification for test set from training set using Rcpp. For each row of the test set, the k nearest (in Euclidean distance) training set vectors are found, and the classification is decided by majority vote.
#' @param X matrix of training set cases
#' @param y label of true classification of training set
#' @param Z matrix of test set cases
#' @param n_classes number of classes in y
#' @param k number of neighbours considerd
#' @return dist Euclidean distance matrix
#' @return results label of classification of test set
#' @examples
#' \dontrun{
#' X<-matrix(c(1:12),ncol=2)
#' y<-c(0,0,0,1,1,1)
#' Z<-matrix(c(2,6,7,11),ncol=2)
#' res<-KNN(X,y,Z,2,k=3)
#' }
#' @export
kNN <- function(X, y, Z, n_classes, k) {
    .Call('_StatComp20036_kNN', PACKAGE = 'StatComp20036', X, y, Z, n_classes, k)
}

